### ISSUE TITLE
TypeError: next[(intermediate value)] is not a function

### ISSUE THREAD

**Issue by zhangda89** [koajs/static#59]
TypeError: next[(intermediate value)] is not a function

**Comment by tejasmanohar** [comment]
Code?

**Comment by coderhaoxin** [comment]
@zhangda89 koa@2?

**Comment by tejasmanohar** [comment]
@zhangda89 You probably just need to use [koa-convert](https://github.com/gyson/koa-convert)

**Comment by tejasmanohar** [comment]
Here's an example, @zhangda89.

```javascript
var Koa = require('koa')
var convert = require('koa-convert')
var statics = require('koa-static')

var app = new Koa()

app.use(convert(statics('./public')))

app.listen(3000)
```

**Comment by zhangda89** [comment]
ok, thanks, it works @tejasmanohar

**Comment by zhangda89** [comment]
@coderhaoxin Yes, it is koa@2

**Comment by tejasmanohar** [comment]
Yep, that's it. A *lot* of the official middleware has not been updated for Koa 2.x.x yet, as it's still in alpha. Many of them have open PRs (and more PRs are obviously appreciated). You will have to use koa-convert in order to convert koa 1.x.x middleware to be compatible w/ 2.x.x and this should work for most all things (but  check the implementation yourself and ask questions if you have any :))
